--- #signifise yml file
# name that is going to appear in github actions
name: Checks 

#trigger
on: [push]

jobs:
  test-lint: #id of the job 
    name: Test and Lint 
    runs-on: ubuntu-20.04
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v1 #Predefined action used for login on docker hub
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout #checkout the code
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"